baseurl = "https://sprky.co"
title = "sprky.co"
theme = "vec"
languageCode = "en-us"
paginate = 5
# Enable comments by entering your Disqus shortname
#disqusShortname = "Your Disqus shortname"
publishDir = "docs"
# Enable analytics by entering your Google Analytics tracking ID
#googleAnalytics = "Your Google Analytics tracking code"
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "whoami"
    weight = 1
    url = "/dywood"
    [[menu.main]]
    name = "talks"
    weight =  2
    url = "/talks"
  [[menu.main]]
    name = "appsecVaudeville"
    weight = 3
    url = "/appsecVaudeville/insecureCodePrimer"
  
[params]
  Keywords = "appsec"
  Description = "Application Security Rants"
  
  Avatar = "img/logo.png"
  SelfIntro = "Professional Technology Critic"
  Email = "cody@sprky.co"
  
  GithubID = "sprkyco"
  TwitterID = "sprkyco"
  LinkedInID = "sprkyco"